language: node_js
addons:
  apt:
    packages:
    - sshpass
node_js:
  - "stable"
dist: trusty
branches:
  only:
  - master
script:
  - npm run build
after_success:
  - sshpass -p $FTP_PASSWORD scp -r $FTP_USER@e-sport.ee:web/volunteer/ build/;