language: node_js
node_js:
  - "stable"
dist: trusty
branches:
  only:
  - master
script:
  - npm run build
after_success:
  - find build -type f -exec curl -u $FTP_USER:$FTP_PASSWORD --ftp-create-dirs -T {} sftp://e-sport.ee/web/volunteer/{} \;