language: node_js
addons:
  apt:
    packages:
    - rsync
    - sshpass
sudo: true
dist: trusty
node_js:
  - "stable"
branches:
  only:
  - master
script:
  - npm run build
after_success:
  - rsync -ratlz --rsh="sshpass -p $FTP_PASSWORD ssh -o StrictHostKeyChecking=no -l $FTP_USER" e-sport.ee/web/volunteer:web/volunteer build