language: node_js
sudo: false
node_js:
  - "stable"
branches:
  only:
  - master
script:
  - npm run build
after_success:
  - find build -type f -exec curl -u $FTP_USER:$FTP_PASSWORD --ftp-create-dirs -T {} ftp://e-sport.ee/web/volunteer/{} \;