language: node_js
addons:
  apt:
    packages:
    - sshpass
    - curl
sudo: true
dist: trusty
node_js:
  - "stable"
branches:
  only:
  - master
script:
  - npm run build
after_success:
  - find build -type f -exec curl --insecure -u $FTP_USER:$FTP_PASSWORD --ftp-create-dirs -T {} sftp://e-sport.ee/web/volunteer/{} \;